apps/products/urls.py
# Copyright (c) 2020 by Abdullah Alnuaimi
# SPDX-License-Identifier: MIT

from django.urls import path

from .views import ProductListView, ProductDetailView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

config/urls.py
# Copyright (c) 2020 by Abdullah Alnuaimi
# SPDX-License-Identifier: MIT

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('apps.products.urls')),
]

if settings.DEBUG:

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
# Copyright (c) 2020 by Abdullah Alnuaimi
# SPDX-License-Identifier: MIT

from django.db import models
from django.urls import reverse_lazy

from .signals import (
    delete_image_post_delete_receiver,
    delete_old_image_pre_save_receiver,
    generate_slug_pre_save_receiver,
)


class ProductOrigin(models.Model):
    name = models.CharField(max_length=50, unique=True, help_text='eg: Spanish, Indian, Iraqi...')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name
    

class ProductType(models.Model):
    name = models.CharField(max_length=50, unique=True, help_text='eg: Ceramic, Porsilan, Marmar...')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class ProductArea(models.Model):
    area = models.CharField(max_length=50, unique=True, help_text='eg: 24cm x 24cm, 60cm x 60cm...')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.area


class ProductColor(models.Model):
    name = models.CharField(max_length=50, unique=True, help_text='eg: White, Yellow, Red...')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, allow_unicode=True)
    description = models.TextField()
    price = models.PositiveIntegerField()
    old_price = models.PositiveIntegerField(null=True, blank=True)
    image = models.ImageField(upload_to='images')

    origin = models.ForeignKey(ProductOrigin, on_delete=models.SET)
    type = models.ForeignKey(ProductType, on_delete=models.SET)
    area = models.ForeignKey(ProductArea, on_delete=models.SET)
    color = models.ForeignKey(ProductColor, on_delete=models.SET)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name[:50]

    def get_absolute_url(self):
        return reverse_lazy('products:detail', kwargs={'slug': self.slug})


# Signals
models.signals.post_delete.connect(delete_image_post_delete_receiver, sender=Product)
models.signals.pre_save.connect(delete_old_image_pre_save_receiver, sender=Product)
models.signals.pre_save.connect(generate_slug_pre_save_receiver, sender=Product)

apps/products/views.py
# Copyright (c) 2020 by Abdullah Alnuaimi
# SPDX-License-Identifier: MIT

from django.views.generic import DetailView

from django_filters.views import FilterView

from .filters import Product, ProductFilter


class ProductListView(FilterView):
    model = Product
    filterset_class = ProductFilter
    template_name = 'products/product_list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET:
            query_dect = self.request.GET.copy()
            # print(query_dect)
            if self.request.GET.get('page'):
                del query_dect['page']
                # print(query_dect)
            context['querystring'] = query_dect.urlencode()
            # print(query_dect.urlencode())
        return context


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'


# Resources:
# Source1: https://stackoverflow.com/questions/51389848/how-can-i-use-pagination-with-django-filter

templates/base.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% load static %}
<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Fashi is a productfolio created by using django framework" />
        <meta name="keywords" content="fashi, django, framework, ecommerce, shop, products" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{% block title %}Fashi{% endblock %}</title>

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" />

        <!-- Css Styles -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body>

        <!-- Page Preloder -->
        <div id="preloder">
            <div class="loader"></div>
        </div>

        {% include 'includes/header.html' %}

        {% block breadcrumb %}{% endblock %}

        <section class="product-shop spad">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </section>

        {% include 'includes/footer.html' %}

        <!-- Js Plugins -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/jquery.slicknav.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/includes/footer.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% load static flatpages %}

{% get_flatpages as flatpages %}

<footer class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="footer-left">
                    <div class="footer-logo">
                        <a href="{% url 'products:list' %}" title="Fashi">
                            <img src="{% static 'img/footer-logo.png' %}" alt="Fashi Logo" />
                        </a>
                    </div>
                    <ul>
                        <li>Address: 60-49 Road 11378 New York</li>
                        <li>Phone: +65 11.188.888</li>
                        <li>Email: hello.colorlib@gmail.com</li>
                    </ul>
                    <div class="footer-social">
                        <a href="#" title="Facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" title="Instagram"><i class="fa fa-instagram"></i></a>
                        <a href="#" title="Twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="footer-widget">
                    <h5>Information</h5>
                    <ul>
                        {% for page in flatpages %}
                        <li>
                            <a href="/pages{{ page.url }}" title="{{ page.title }}">{{ page.title }}</a>
                        </li>
                        {% endfor %}
                        <li><a href="#" title="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-5 offset-lg-1">
                <div class="newslatter-item">
                    <h5>Join Our Newsletter Now</h5>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#" class="subscribe-form">
                        <input type="text" placeholder="Enter Your Mail">
                        <button type="button">Subscribe</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-reserved">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text">
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% load static flatpages %}

{% get_flatpages as flatpages %}

<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="ht-left">
                <div class="mail-service">
                    <i class="fa fa-envelope"></i>
                    <span>hello.colorlib@gmail.com</span>
                </div>
                <div class="phone-service">
                    <i class="fa fa-phone"></i>
                    <span>+65 11.188.888</span>
                </div>
            </div>
            <div class="ht-right">
                {% if user.is_staff or user.is_superuser %}
                <a href="{% url 'admin:index' %}" class="login-panel" target="_blank">
                    <i class="fa fa-dashboard"></i>Dashboard
                </a>
                {% endif %}
                <div class="top-social">
                    <a href="#" title="Facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" title="Twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" title="Instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="inner-header">
            <div class="row">
                <div class="col-4 col-md-6">
                    <div class="logo">
                        <a href="{% url 'products:list' %}" title="Fashi">
                            <img src="{% static 'img/logo.png' %}" alt="Fashi Logo" />
                        </a>
                    </div>
                </div>
                <div class="col-8 col-md-6">
                    <div class="advanced-search">
                        <form action="{% url 'products:list' %}" class="input-group">
                            <input type="search" name="search" id="search" value="{{ request.GET.search }}" placeholder="Search Product Name Here..." />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="nav-item">
        <div class="container">
            <nav class="nav-menu mobile-menu">
                <ul>
                    <li><a href="{% url 'products:list' %}" title="Home">Home</a></li>
                    {% for page in flatpages %}
                    <li>
                        <a href="/pages{{ page.url }}" title="{{ page.title }}">{{ page.title }}</a>
                    </li>
                    {% endfor %}
                    <li><a href="#" title="Contact">Contact</a></li>
                </ul>
            </nav>
            <div id="mobile-menu-wrap"></div>
        </div>
    </div>
</header>

templates/products/includes/product.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

<div class="col-lg-4 col-sm-6">
    <div class="product-item">
        <div class="pi-pic">
            <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
                {# <img src="{{ product.image.url }}" alt="Product Image" /> #}
                <img src="static/img/product.jpg" alt="Product Image" />
            </a>
        </div>
        <div class="pi-text">
            <div class="catagory-name">{{ product.area }}</div>
            <a href="{{ product.get_absolute_url }}" title="{{ product.name }}">
                <h5>{{ product.name }}</h5>
            </a>
            <div class="product-price">
                ${{ product.price }}
                {% if product.old_price %}
                <span>${{ product.old_price }}</span>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/products/includes/sidebar.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% load widget_tweaks %}

<div class="col-lg-3 col-md-6 col-sm-8 order-2 order-lg-1 produts-sidebar-filter">
    <form method="get">
        {% for field in filter.form %}
            {% if field.label != 'Name' and field.label != 'Sort By' %}
                <div class="filter-widget">
                    <h4 class="fw-title">{{ field.label }}</h4>
                    {% if field.label == 'Price' %}
                        <div class="filter-range-wrap">
                            <div class="range-slider">
                                <div class="price-input">
                                    {% for input in field %}
                                        {{ input.tag }}
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="price-range" data-min="30" data-max="120"></div>
                        </div>
                    {% else %}
                    <div class="fw-brand-check">
                        {% for choice in field %}
                        <div class="bc-item">
                            <label>
                                {{ choice.tag }} {{ choice.choice_label }}
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
        <button type="submit" class="btn filter-btn">Filter</button>
    </form>
</div>

templates/products/product_detail.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% extends 'base.html' %}

{% block title %}{{ product.name }} - {{ block.super }}{% endblock %}

{% block breadcrumb %}
<div class="breacrumb-section">
    <div class="container">
        <div class="breadcrumb-text product-more">
            <a href="{% url 'products:list' %}"><i class="fa fa-home"></i> Home</a>
            <span>{{ product.name }}</span>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="product-pic-zoom">
                {#<img class="product-big-img" src="{{ product.image.url }}" alt="Product Image" />#}
                <img class="product-big-img" src="/static/img/product.jpg" alt="Product Image" />
            </div>
        </div>
        <div class="col-lg-6">
            <div class="product-details">
                <div class="pd-title">
                    <h3>{{ product.name }}</h3>
                </div>
                <div class="pd-desc">
                    <p>{{ product.description }}</p>
                    <h4>
                        ${{ product.price }}
                        {% if product.old_price %}
                        <span>${{ product.old_price }}</span>
                        {% endif %}
                    </h4>
                </div>
                <ul class="pd-tags">
                    <li><span>ORIGIN</span>: {{ product.origin.name }}</li>
                    <li><span>TYPE</span>: {{ product.type.name }}</li>
                    <li><span>AREA</span>: {{ product.area }}</li>
                    <li><span>COLOR</span>: {{ product.color.name }}</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/product_list.html
{# Copyright (c) 2020 by Abdullah Alnuaimi #}
{# SPDX-License-Identifier: MIT #}

{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Fashi is a productfolio created by using django framework - {{ block.super }}{% endblock %}

{% block content %}
    <div class="row">
        {% if object_list %}
            {% include 'products/includes/sidebar.html' %}
            <div class="col-lg-9 order-1 order-lg-2">
                <div class="product-show-option">
                    <div class="row">
                        <div class="col-md-7">
                            <form method="get">
                                {% if filter.form.ordering %}
                                <div class="select-option">
                                    <select name="ordering" id="ordering" class="sorting">
                                        {% for option in filter.form.ordering %}
                                            {{ option.tag }}
                                        {% endfor %}
                                    </select>
                                    <button type="submit" class="btn filter-btn">Sort</button>
                                </div>
                                {% endif %}
                            </form>
                        </div>
                        <div class="col-md-5 text-right d-none d-md-block">
                            <p>Show 01- 09 Of 36 Product</p>
                        </div>
                    </div>
                </div>

                <div class="product-list">
                    <div class="row">
                        {% for product in object_list %}
                            {% include 'products/includes/product.html' %}
                        {% endfor %}
                    </div>
                </div>

                {% if is_paginated %}
                    {% if page_obj.has_next %}
                    <div class="loading-more">
                        <a href="?page={{ page_obj.next_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" title="Loading More">
                            Loading More
                        </a>
                    </div>
                    {% endif %}
                {% endif %}

            </div>
        {% endif %}
    </div>
{% endblock %}